# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    #Give the container a name(Any)
    #container_name: NoteAdd
    # https://stackoverflow.com/a/71027261
    user: ${MY_UID}:${MY_GID}
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./package.json:/app/package.json
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./note-template:/app/note-template
      - ./docker-scripts:/app/docker-scripts
      - ./config:/app/config
      - ${NOTES_PATH}:/app/notes:rw
    environment:
      - DISPLAY=${DISPLAY}
      - GUEST_NOTE_PATH=${GUEST_NOTE_PATH}
      - TZ=${TZ}
    #Mount port 1000 on the container side to port 8080 on the host side.
    #ports:
    #  - "8080:8080"
